repos:
  # black
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/prospector
    rev: 1.9.0
    hooks:
      - id: prospector